/* SPDX-License-Identifier: MIT
 *
 * Copyright (C) 2019 WireGuard LLC. All Rights Reserved.
 */

package winwfp

import "fmt"

// Defined in fwpmtypes.h
type FwpmFilterFlags uint32

const (
	FWPM_FILTER_FLAG_NONE                                FwpmFilterFlags = 0x00000000
	FWPM_FILTER_FLAG_PERSISTENT                          FwpmFilterFlags = 0x00000001
	FWPM_FILTER_FLAG_BOOTTIME                            FwpmFilterFlags = 0x00000002
	FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT                FwpmFilterFlags = 0x00000004
	FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT                  FwpmFilterFlags = 0x00000008
	FWPM_FILTER_FLAG_PERMIT_IF_CALLOUT_UNREGISTERED      FwpmFilterFlags = 0x00000010
	FWPM_FILTER_FLAG_DISABLED                            FwpmFilterFlags = 0x00000020
	FWPM_FILTER_FLAG_INDEXED                             FwpmFilterFlags = 0x00000040
	FWPM_FILTER_FLAG_HAS_SECURITY_REALM_PROVIDER_CONTEXT FwpmFilterFlags = 0x00000080
	FWPM_FILTER_FLAG_SYSTEMOS_ONLY                       FwpmFilterFlags = 0x00000100
	FWPM_FILTER_FLAG_GAMEOS_ONLY                         FwpmFilterFlags = 0x00000200
	FWPM_FILTER_FLAG_SILENT_MODE                         FwpmFilterFlags = 0x00000400
	FWPM_FILTER_FLAG_IPSEC_NO_ACQUIRE_INITIATE           FwpmFilterFlags = 0x00000800
)

func (ff FwpmFilterFlags) String() string {
	switch ff {
	case FWPM_FILTER_FLAG_NONE:
		return "FWPM_FILTER_FLAG_NONE"
	case FWPM_FILTER_FLAG_PERSISTENT:
		return "FWPM_FILTER_FLAG_PERSISTENT"
	case FWPM_FILTER_FLAG_BOOTTIME:
		return "FWPM_FILTER_FLAG_BOOTTIME"
	case FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT:
		return "FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT"
	case FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT:
		return "FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT"
	case FWPM_FILTER_FLAG_PERMIT_IF_CALLOUT_UNREGISTERED:
		return "FWPM_FILTER_FLAG_PERMIT_IF_CALLOUT_UNREGISTERED"
	case FWPM_FILTER_FLAG_DISABLED:
		return "FWPM_FILTER_FLAG_DISABLED"
	case FWPM_FILTER_FLAG_INDEXED:
		return "FWPM_FILTER_FLAG_INDEXED"
	case FWPM_FILTER_FLAG_HAS_SECURITY_REALM_PROVIDER_CONTEXT:
		return "FWPM_FILTER_FLAG_HAS_SECURITY_REALM_PROVIDER_CONTEXT"
	case FWPM_FILTER_FLAG_SYSTEMOS_ONLY:
		return "FWPM_FILTER_FLAG_SYSTEMOS_ONLY"
	case FWPM_FILTER_FLAG_GAMEOS_ONLY:
		return "FWPM_FILTER_FLAG_GAMEOS_ONLY"
	case FWPM_FILTER_FLAG_SILENT_MODE:
		return "FWPM_FILTER_FLAG_SILENT_MODE"
	case FWPM_FILTER_FLAG_IPSEC_NO_ACQUIRE_INITIATE:
		return "FWPM_FILTER_FLAG_IPSEC_NO_ACQUIRE_INITIATE"
	default:
		return fmt.Sprintf("FwpmFilterFlags_UNKNOWN(%d)", ff)
	}
}
